export const INI_RULES: Record<string, { title: string; label?: string; description?: string; rationale?: string; tone: string }> = {
  R001: { title: "Hardcoded DDC Path", tone: "critical" },
  R002: { title: "User-level DDC override", tone: "critical" },
  R003: { title: "Unreachable cache path", tone: "critical" },
  R004: { title: "Mapped drive path", tone: "warning" },
  R005: { title: "Deprecated CVar", tone: "warning" },
  R006: { title: "Missing env var", tone: "warning" },
  R007: { title: "Healthy EnvPathOverride", tone: "healthy" },
  R008: { title: "PSO precaching disabled", tone: "critical" },
  R009: { title: "PSO compile disabled", tone: "warning" },
  R010: { title: "Global shader PSO disabled", tone: "warning" },
  R011: { title: "Shared backend Type missing or wrong", tone: "critical" },
  R012: { title: "Shared DDC marked ReadOnly", tone: "warning" },
  R013: { title: "Clean=true wipes Shared every launch", tone: "critical" },
  R014: { title: "Flush=true clears cache on exit", tone: "warning" },
  R015: { title: "DeleteUnused not configured", tone: "warning" },
  R016: { title: "UnusedFileAge out of range", tone: "warning" },
  R017: { title: "FoldersToClean out of range", tone: "warning" },
  R018: { title: "MaxFileChecksPerSec out of range", tone: "warning" },
  R019: { title: "ConsiderSlowAt out of range", tone: "warning" },
  R020: { title: "PromptIfMissing=true blocks unattended starts", tone: "critical" },
  R021: { title: "Shared Path missing or not UNC", tone: "critical" },
  R022: { title: "EnvPathOverride not set", tone: "warning" },
  R023: { title: "EditorOverrideSetting not declared", tone: "info" },
  R024: { title: "r.ShaderPipelineCache.Enabled not 1", tone: "critical" },
  R025: { title: "Project-level Pref masks env var", tone: "critical" },
  SCAN_ERROR: { title: "Read skipped", tone: "info" },
};
