# Creates a managed SMB share on a remote host with a dedicated ddc-svc account
# (Mode B). Production-grade path: dedicated local account on the host, share
# authorized only for that account.
# Parameters:
#   -HostName <string>
#   -ShareName <string>
#   -LocalPath <string>
#   -SvcUsername <string>          e.g. "ddc-svc"
#   -SvcPassword <string>          24-byte random generated by the operator
#   [-Username <string>] [-Password <string>]   operator admin cred for host
# Output: JSON { ok, unc_path, message }
# Requires: WinRM session user (or supplied credential) is admin on the remote host.

param(
    [Parameter(Mandatory=$true)] [string]$HostName,
    [Parameter(Mandatory=$true)] [string]$ShareName,
    [Parameter(Mandatory=$true)] [string]$LocalPath,
    [Parameter(Mandatory=$true)] [string]$SvcUsername,
    [Parameter(Mandatory=$true)] [string]$SvcPassword,
    [string]$Username,
    [string]$Password
)

[Console]::OutputEncoding=[System.Text.Encoding]::UTF8; chcp 65001 | Out-Null

$ErrorActionPreference = 'Stop'

function Build-CredentialOrNull {
    param([string]$User, [string]$Pass)
    if ([string]::IsNullOrEmpty($User) -or [string]::IsNullOrEmpty($Pass)) { return $null }
    $User = $User.Trim()
    if ([string]::IsNullOrEmpty($User)) { return $null }
    if ($User.StartsWith(".\") -or $User.StartsWith("./")) { $User = $User.Substring(2) }
    $secure = ConvertTo-SecureString -String $Pass -AsPlainText -Force
    return New-Object System.Management.Automation.PSCredential($User, $secure)
}

try {
    $script = {
        param($ShareName, $LocalPath, $SvcUsername, $SvcPasswordPlain)
        if (-not (Test-Path $LocalPath)) {
            New-Item -ItemType Directory -Path $LocalPath -Force | Out-Null
        }
        $svcSecure = ConvertTo-SecureString -String $SvcPasswordPlain -AsPlainText -Force
        $existingUser = Get-LocalUser -Name $SvcUsername -ErrorAction SilentlyContinue
        if ($existingUser) {
            Set-LocalUser -Name $SvcUsername -Password $svcSecure -PasswordNeverExpires $true
        } else {
            New-LocalUser -Name $SvcUsername -Password $svcSecure -PasswordNeverExpires -AccountNeverExpires -UserMayNotChangePassword -Description 'UECM share account (Mode B)' | Out-Null
            Add-LocalGroupMember -Group 'Users' -Member $SvcUsername -ErrorAction SilentlyContinue
        }
        icacls $LocalPath /grant "${SvcUsername}:(OI)(CI)F" | Out-Null
        $existing = Get-SmbShare -Name $ShareName -ErrorAction SilentlyContinue
        if ($existing) {
            Remove-SmbShare -Name $ShareName -Force
        }
        New-SmbShare -Name $ShareName -Path $LocalPath -FullAccess $SvcUsername -Description 'UECM managed DDC share (Mode B)' | Out-Null
        return "\\$($env:COMPUTERNAME)\$ShareName"
    }
    $cred = Build-CredentialOrNull -User $Username -Pass $Password
    $invokeArgs = @{
        ComputerName = $HostName
        ScriptBlock  = $script
        ArgumentList = @($ShareName, $LocalPath, $SvcUsername, $SvcPassword)
        ErrorAction  = 'Stop'
        Authentication = 'Negotiate'
    }
    if ($cred) { $invokeArgs['Credential'] = $cred }
    $remoteResult = Invoke-Command @invokeArgs
    $unc = "$remoteResult"
    @{ ok = $true; unc_path = $unc; message = "Mode B share created: $unc as $SvcUsername" } | ConvertTo-Json -Compress
}
catch {
    @{ ok = $false; unc_path = ""; message = $_.Exception.Message } | ConvertTo-Json -Compress
    exit 1
}
